services:
  mongodb:
    image: mongo
    container_name: webflux-demo-mongodb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
